### PR TITLE
fix andhra scraper

### PR DESCRIPTION
**Pull request by ramSeraph**
The doc identifiers appear to have changed, they now are very long. Ex: `raw/andhra/2024-06-07/eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwZWdhemV0dGUuY2dnLmdvdi5pbi9zZWFyY2hBbGxHYXpldHRlcyIsImlhdCI6MTcxODkwNTMzNCwic3ViIjoiL1VwbG9hZHMvQVBHQVpFVFRFL2dhemV0dGVzLzE3MTc3Mzk3MzEyMDcucGRmIn0.WsNUXFj5a1EvbgKcP6RxCm7K-sN70pbF1RP0-V5GA3o.pdf`. Not sure if this is going to cause problems in IA.

### CODE REVIEW

**Comment by sushant354** [comment]
Yes. We need the same identifiers as earlier. Can you see if that can be fixed?
Screenshot from 2024-06-21 10-57-30

**Comment by ramSeraph** [comment]
I will see what I can do, not sure though, I need to understand what numbers the older identifiers represent. 

A few things I need to understand: 

1) Given that the docid has gone into the identifier in IA like( https://archive.org/details/in.gazette.andhra.2019-05-08.5046 ). I am guessing this is not something that can be backfilled. can you confirm?

2) Is the id "in.gazette.andhra.2019-05-08.5046" being used to check if an upload has already been executed?

3) what are the limitations on identifier length/constitution in IA?

I can probably figure these out from code and google, If you know the answers offhand, do drop an answer.

Also, let's close this PR, I will make the necessary changes in a different one.

**Comment by sushant354** [comment]
1. Cannot be back-filled.
2. Yes. ID is for checking what has been uploaded.
3. It should be readable. And should be replicated across crawler changes

**Comment by ramSeraph** [comment]
I have thought about it. I will close this PR for now. Will resubmit later when I have an answer to the problem.

**Pull request closed without merging**
